spring:
  profiles:
    active: dev
  
  # Configuración de la base de datos
  datasource:
    url: jdbc:mysql://localhost:3306/ovycar_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # Configuración JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  # Cargar datos de ejemplo
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
  
  # Configuración de seguridad (temporalmente deshabilitada para desarrollo)
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Configuración del servidor
server:
  port: 8080

# Configuración de logging
logging:
  level:
    com.talleres.ovycar: DEBUG
    org.springframework.security: DEBUG 